language: node_js
dist: xenial

node_js:
  - "12"
  - "13"
  - "14"

before_script:
  - npm run setup

script:
  - npm run get -- --includeLanguages en
  - npm run transform

after_script:
  - npm run export -- --mulOnly
